<template>
  <div class="policy-container">
    <div class="form-container">
      <el-form :model="projectForm" :rules="rules" label-position="top" ref="projectForm" label-width="100px">
        <el-form-item label="Service Deployment Timeout Settings（Minute）" prop="timeout">
          <el-input v-model.number="projectForm.timeout"></el-input>
        </el-form-item>
        <el-form-item prop="auto_deploy.enable" v-if="showAutoUpdate">
          <span slot="label">
            <span>Service Auto Update</span>
            <el-tooltip effect="dark" content="After turning on automatic updates，When service configuration changes，Zadig It will be automatically deployed to all environments in the project" placement="top">
              <i class="pointer el-icon-warning"></i>
            </el-tooltip>
          </span>
          <span>Turn on automatic updates</span>
          <el-switch v-model="projectForm.auto_deploy.enable" />
        </el-form-item>
        <el-form-item label="Deliverable Naming Rules Settings">
          <span slot="label">
            Deliverable Naming Rules Settings
            <el-tooltip effect="dark" placement="top">
              <div slot="content">
                Mirror And TAR Package rules can be generated by assembling variables and constants：
                <br />
                <div v-for="item in tipList" :key="item.key" >
                  <span v-html="item.key" style="display: inline-block; width: 140px;"></span> <span>{{item.label}}</span>
                </div>
                <br />
                <div>Notice：</div>
                <div>- Constant characters can only be uppercase and lowercase letters、Number、Dash、Underscore And Dot，Which Is [a-zA-Z0-9_.-]</div>
                <div>- The first character of a constant character begins with an uppercase or lowercase letter or number，The Maximum Length Is 127 Characters</div>
                <div>- If other code sources are used， <span v-html="'{{.REPO_PR}}、{{.REPO_COMMIT_ID}}'"></span> Variable Not Supported</div>
              </div>
              <i class="el-icon-question"></i>
            </el-tooltip>
          </span>
          <CusDeliverable
            :customImageRule="projectForm.custom_image_rule"
            :customTarRule="projectForm.custom_tar_rule"
            ref="cusDeliverable"
          />
        </el-form-item>
      </el-form>
    </div>
    <div class="operation-container">
      <el-button type="primary" size="small" @click="submitForm('projectForm')">Save Strategy</el-button>
    </div>
  </div>
</template>
<script>
import { getSingleProjectAPI, updateSingleProjectAPI } from '@api'
import CusDeliverable from '../../../detail_ope/components/cusDeliverable.vue'
const validateDeployTimeout = (rule, value, callback) => {
  const reg = /^[0-9]+.?[0-9]*/
  if (!reg.test(value)) {
    callback(new Error('Time Should Be A Number'))
  } else {
    if (value > 0) {
      callback()
    } else {
      callback(new Error('Please enter the correct time range'))
    }
  }
}
export default {
  components: {
    CusDeliverable
  },
  props: {
    service: {
      type: Array,
      default: () => [
        { build_name: '' }
      ]
    }
  },
  data () {
    return {
      projectForm: {
        timeout: null,
        custom_image_rule: {},
        auto_deploy: {
          enable: false
        }
      },
      rules: {
        timeout: [
          {
            required: true,
            trigger: 'change',
            validator: validateDeployTimeout
          }
        ]
      },
      tipList: [
        { key: '{{.TIMESTAMP}}', label: 'Timestamp' },
        { key: '{{.TASK_ID}}', label: 'Workflow Tasks ID' },
        { key: '{{.REPO_BRANCH}}', label: 'Code Branch Name' },
        { key: '{{.REPO_PR}}', label: 'Code PR ID' },
        { key: '{{.REPO_TAG}}', label: 'Code TAG' },
        { key: '{{.REPO_COMMIT_ID}}', label: 'Code Commit ID' },
        { key: '{{.PROJECT}}', label: 'Project Name' },
        { key: '{{.SERVICE}}', label: 'Service Name' },
        { key: '{{.IMAGE_NAME}}', label: 'Image Name' },
        { key: '{{.ENV_NAME}}', label: 'Environment Name' }
      ]
    }
  },
  computed: {
    projectName () {
      return this.$route.params.project_name
    },
    showAutoUpdate () {
      const project = this.$store.getters.projectList.find(
        project => project.name === this.projectName
      )
      if (!this.projectName) {
        return false
      } else if (project && (project.deployType === 'helm' || project.deployType === 'k8s')) {
        return true
      } else {
        return false
      }
    }
  },
  methods: {
    getPolicy (projectName) {
      getSingleProjectAPI(projectName).then(res => {
        this.projectForm = res
        if (!res.timeout) {
          this.$set(this.projectForm, 'timeout', 10)
        }
        if (!res.auto_deploy) {
          this.$set(this.projectForm, 'auto_deploy', { enable: false })
        }
      })
    },
    updatePolicy (projectName, payload) {
      updateSingleProjectAPI(projectName, payload).then(res => {
        this.$message({
          type: 'success',
          message: 'Policy updated successfully'
        })
      })
    },
    submitForm (formName) {
      this.$refs[formName].validate(valid => {
        if (valid) {
          this.$refs.cusDeliverable.saveConfig()
          this.projectForm.custom_image_rule = this.$refs.cusDeliverable.custom_image_rule
          this.projectForm.custom_tar_rule = this.$refs.cusDeliverable.custom_tar_rule
          this.updatePolicy(this.projectForm.product_name, this.projectForm)
        } else {
          return false
        }
      })
    },
    resetForm (formName) {
      this.$refs[formName].resetFields()
    }
  },
  mounted () {
    this.getPolicy(this.projectName)
  }
}
</script>
<style lang="less">
.policy-container {
  display: flex;
  flex-direction: column;
  height: 100%;

  .form-container {
    display: flex;
    flex: 1;
    box-sizing: border-box;
    width: 100%;
    margin-bottom: 10px;
    padding: 10px;
    overflow: auto;

    .el-form {
      width: 100%;

      /deep/.el-popper.tip {
        .tooltip-key {
          display: inline-block;
          width: 280px !important;
        }
      }
    }
  }

  .operation-container {
    display: flex;
    flex-direction: row;
    align-items: flex-end;
    height: 32px;
  }
}
</style>
